[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"

[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

[build.processing.images]
  compress = true

# Configurações de otimização de assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.webp"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.avif"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Headers de segurança para todas as páginas
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = """
      default-src 'self';
      script-src 'self' 'unsafe-inline' 'unsafe-eval' 
        https://*.googletagmanager.com 
        https://*.google-analytics.com
        https://*.analytics.google.com
        https://*.facebook.com
        https://*.facebook.net
        https://*.fbcdn.net
        https://unpkg.com;
      style-src 'self' 'unsafe-inline' 
        https://fonts.googleapis.com;
      img-src 'self' data: https: 
        https://*.google-analytics.com
        https://*.googletagmanager.com
        https://*.facebook.com
        https://*.fbcdn.net
        https://*.doubleclick.net;
      font-src 'self' data: 
        https://fonts.gstatic.com;
      connect-src 'self' 
        https://*.google-analytics.com
        https://*.analytics.google.com
        https://*.facebook.com
        https://api.iagomilionario.com
        https://*.doubleclick.net;
      frame-src 'self' 
        https://*.facebook.com
        https://*.doubleclick.net;
      object-src 'none';
      base-uri 'self';
      form-action 'self';
      """

# Redirecionamento de 404
[[redirects]]
  from = "/*"
  to = "/404"
  status = 404

# Cabeçalhos para habilitar a compressão em produção
[[headers]]
  for = "/*"
  [headers.values]
    Content-Encoding = "br"
    Content-Type = "text/html; charset=UTF-8"
    Cache-Control = "public, max-age=2592000"

# Configuração específica para servir arquivos estáticos comprimidos
[[headers]]
  for = "/*.js"
  [headers.values]
    Content-Encoding = "br"
    Content-Type = "application/javascript; charset=UTF-8"
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*.css"
  [headers.values]
    Content-Encoding = "br"
    Content-Type = "text/css; charset=UTF-8"
    Cache-Control = "public, max-age=31536000"

# Fallback para browsers que não suportam Brotli
[[redirects]]
  from = "/*.js"
  to = "/:splat.js.gz"
  status = 200
  force = false
  conditions = {Accept-Encoding = "gzip"}
  headers = {Content-Encoding = "gzip", Content-Type = "application/javascript; charset=UTF-8"}

[[redirects]]
  from = "/*.css"
  to = "/:splat.css.gz"
  status = 200
  force = false
  conditions = {Accept-Encoding = "gzip"}
  headers = {Content-Encoding = "gzip", Content-Type = "text/css; charset=UTF-8"} 